baseURL: "/"
languageCode: en-gb
title: David Rocha
theme: PaperMod

paginate: 5
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

menu:
  main:
    - name: Archive
      url: archives
      weight: 3
    - name: Posts
      url: posts/
      weight: 1
    - name: Projects
      url: projects/
      weight: 2
    - name: Resumé
      url: /documents/cv.pdf
      weight: 4

params:
  homeInfoParams:
    imageUrl: "1690057149591.jpeg"
    Title: "About me"
    Content: >
      - I am a software engineer with a deep passion for game development.

      - 

      - Gaming played a pivotal role in my childhood, shaping my imagination and guiding my career path. I strive to create experiences that resonate with players in the same way the games of my youth influenced me.

      -

      - My vision is to craft games that inspire, connect, and leave a lasting impression on players of all ages.

      -

      - Currently working as a Junior Software Engineer @ [Arkadium](https://www.arkadium.com/).

  # Social links
  socialIcons:
    - name: github
      url: "https://github.com/davidrocha9"
    - name: linkedin
      url: "https://www.linkedin.com/in/josedavidrocha/"
    - name: email
      url: "mailto:davidsoutorocha@gmail.com"
    - name: cv
      url: /documents/cv.pdf

  sectionPagesMenu: main

  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
